[workspace]
members = [
  "mandy-bin",
  "components/utils",
  "components/extras",
  "components/merrors",
  "components/compiler",
  "components/get_data",
  "components/variables",
  "components/processors",
]

[profile.release.mandy-bin]
strip = true
opt-level = "z"
lto = true
codegen-units = 1