[workspace]
members = [
  "utils",
  "extras",
  "merrors",
  "compiler",
  "get_data",
  "variables",
  "mandy-bin",
  "processors",
]

[profile.release.mandy-bin]
strip = true
opt-level = "z"
lto = true
codegen-units = 1