[package]
name = "mandy"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Angel Dollface"]
description= "A hypersonic static-site generator written in Rust."
homepage = "https://github.com/angeldollface/mandy"
repository = "https://github.com/angeldollface/mandy"
documentation = "https://github.com/angeldollface/mandy"
readme = "README.markdown"
keywords = [
  "site",
  "static",
  "generator"
]
categories = [
  "command-line-utilities"
]
exclude = [  
  "/.github"
]


[[bin]]
name = "mandy"
path = "src/main.rs"

[dependencies]
git2 ="0.17.2"
regex = "1.8.4"
emojis = "0.6.0"
grass = "0.12.4"
liquid = "0.26.4"
serde = "1.0.164"
colorize = "0.1.0"
markdown = "0.3.0"
serde_json = "1.0.79"
serde_derive = "1.0.164"
yaml-front-matter = "0.1.0"
cleasy = { git = "https://github.com/angeldollface/cleasy", version = "1.5.0" }
coutils = { git = "https://github.com/angeldollface/coutils", version = "1.3.0" }

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
