[target.x86_64-unknown-linux-musl]
linker = "/usr/local/bin/gcc-13"

#TARGET_CC=x86_64-linux-musl-gcc cargo build --release --target x86_64-unknown-linux-musl
#brew install filosottile/musl-cross/musl-cross