[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Angel Dollface <youreccentricity@outlook.com>"]
description= "Compiler functions for the Mandy static-site generator."
homepage = "https://github.com/angeldollface/mandy"
repository = "https://github.com/angeldollface/mandy"
documentation = "https://github.com/angeldollface/mandy"
readme = "../README.markdown"

[dependencies]
liquid = "0.26.4"
coutils =  "1.4.0"
utils = { path = "../utils" }
extras = { path = "../extras" }
merrors = { path = "../merrors" }
context = { path = "../context" }
get_data = { path = "../get_data" }
processors = { path = "../processors" }
