on: [push]
env:
  MANDY_ENV: "production"
name: Mandy Release CI
jobs:
    release:
        name: ${{ matrix.target }}
        runs-on: ${{ matrix.os }}
        strategy:
          fail-fast: true
          matrix:
            include:
              - os: ubuntu-latest
                target: x86_64-unknown-linux-gnu
              - os: ubuntu-latest
                target: i686-unknown-linux-gnu
              - os: windows-latest
                target: x86_64-pc-windows-msvc
              - os: windows-latest
                target: i686-pc-windows-msvc
              - os: macos-latest
                target: x86_64-apple-darwin
              - os: macos-latest
                target: aarch64-apple-darwin
        steps:

            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                toolchain: stable
                        
            - name: "Build Mandy."
              uses: actions-rs/cargo@v1
              with:
                command: build
                args: --release
            - name: "Make platformspecific directory."
              run: mkdir ${{ matrix.os }}${{ matrix.target }}
            - name: "Move platformspecific files."
              run: mv target/release ${{ matrix.os }}${{ matrix.target }}
            - name: "Deploy"
              uses: JamesIves/github-pages-deploy-action@v4.2.5
              with:
                branch: v.0.1.0
                folder: ${{ matrix.os }}${{ matrix.target }}
