on: [push]
name: Mandy CI
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: "Build Mandy."
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: "Run Mandy."
        uses: actions-rs/cargo@v1
        with:
          command: run
      - name: "Build Mandy for multiple targets."
        run: "cd scripts && bash build.sh"
